// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v5.27.1
// source: user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { wrappers } from "protobufjs";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface CreateUserDto {
  fullName: string;
  email: string;
  avatarUrl?: string | undefined;
  password: string;
  phoneNumber: string;
}

export interface GetCredentialDto {
  email: string;
}

export interface UpdateUserDto {
  fullName: string;
  avatarUrl?: string | undefined;
  password: string;
  phoneNumber: string;
  isVerified: boolean;
  isActive: boolean;
}

export interface UserFilterDto {
  id?: string | undefined;
  email?: string | undefined;
}

export interface UpdateUserRequest {
  filter: UserFilterDto | undefined;
  updates: UpdateUserDto | undefined;
}

export interface GetUserRequest {
  filter: UserFilterDto | undefined;
  select: string[];
}

export interface UserVM {
  id: string;
  email: string;
  avatarUrl?: string | undefined;
  phoneNumber: string;
  fullName: string;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
  isActive: boolean;
  isVerified: boolean;
}

export interface UserCredentialVM {
  id: string;
  email: string;
  passwordHash: string;
  isActive: boolean;
}

export const USER_PACKAGE_NAME = "user";

wrappers[".google.protobuf.Timestamp"] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;

export interface UserServiceClient {
  create(request: CreateUserDto): Observable<UserVM>;

  getCredential(request: GetCredentialDto): Observable<UserCredentialVM>;

  update(request: UpdateUserRequest): Observable<UserVM>;

  get(request: GetUserRequest): Observable<UserVM>;
}

export interface UserServiceController {
  create(request: CreateUserDto): Promise<UserVM> | Observable<UserVM> | UserVM;

  getCredential(request: GetCredentialDto): Promise<UserCredentialVM> | Observable<UserCredentialVM> | UserCredentialVM;

  update(request: UpdateUserRequest): Promise<UserVM> | Observable<UserVM> | UserVM;

  get(request: GetUserRequest): Promise<UserVM> | Observable<UserVM> | UserVM;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["create", "getCredential", "update", "get"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
